server:
  port: 8000 # 서버 포트 설정
  servlet:
    encoding: # 인코딩 UTF-8 설정
      charset: UTF-8
      enabled: true
      force: true
      force-response: true
      force-request: true
  tomcat:
    uri-encoding: UTF-8

spring:
  mvc:
    static-path-pattern: /static/** # 프론트엔드 영역 static디렉토리
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mitem714285.iptime.org:3306/todolist?useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Seoul&allowMultiQueries=true
    username: mitem714285
    password: TestPassword
  web:
    resources:
      static-locations:
      - classpath:/static/ # 프론트엔드 영역 static디렉토리 시작영역
      add-mappings: true
    
mybatis:
  mapper-locations:
  - /mappers/*.xml